import Head from "next/head";
import Contact from "./components/Contact";
import Cta from "./components/Cta";
import Features from "./components/Features";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Hero from "./components/Hero";
import Pricing from "./components/Pricing";
import Services from "./components/Services";
import Testemonial from "./components/Testemonial";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Features />

      <hr />
      <Hero />
      <hr />

      <Pricing />
      <hr />

      <Testemonial />

      <hr />

      <Cta />
      <hr />

      <Contact />

      <Footer />
    </>
  );
}
